### ISSUE TITLE
node examples errors

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/supercolliderjs-examples#1]
Hi, here are a few examples I tried that didn't work from the node folder. I listed the example name then the error message. I can list them separately if that's more organized but I'll just put them here for now. 

**server-plus/ bus.js**

error:
Unhandled rejection TypeError: server.compileSynthDefs is not a function
    at sc.server.boot.then (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/server/server-plus/bus.js:14:46)
    at tryCatcher (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**music-with-list-patterns-decorators.js**

error:
/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/server/patterns/music-with-list-patterns-decorators.js:66
      yield item;
            ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**music-with-list-patterns-func-wrappers.js**

error:
starts playing for a second then fails, sendosc reads “freq”, null sometimes

**run-sclang-emitter**

error:
Unhandled rejection TypeError: SCLang is not a constructor
    at /Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/lang/run-sclang-emitter.js:21:16
    at tryCatcher (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

lang/sclang-interpret

error:
debug  : {
             "debug": true,
             "echo": false,
             "stdin": false,
             "langPort": 57120,
             "serverPort": 57110,
             "host": "127.0.0.1",
             "protocol": "udp",
             "websocketPort": 4040,
             "sclang": "/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang",
             "scsynth": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/scsynth",
             "sclang_conf": "/Users/tatecarson/Library/Application Support/SuperCollider/sclang_conf.yaml",
             "configPath": null
           }
debug  : init_OSC
debug  : compiling class library...
debug  : initPassOne started
           NumPrimitives = 711
           initPassOne done
           compiling dir: '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/Extensions'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/crucial-library'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/BBCut'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/UGenPatterns'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/XML'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/wslib'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwCommon'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwPrototype'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/JITLibExtensions'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/API'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/MathLib'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/adclib'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/NatureToolkit'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/PitchCircle'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/TuningLib'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/PopUpTreeMenu'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/VectorSpace'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Unit-Lib'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Wavesets'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Feedback'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Ease'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/EnvScaleView'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Ctk'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/redUniverse'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/3Dj'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FileLog'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwGUIEnhancements'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwMixerChannel'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwPatterns'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwTemperament'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Automation'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/mosca'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/TabbedView2'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/TabbedView2_QT'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FancySlider'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FreeAfter.quark'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwVoicer'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/GameLoop'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/AmbIEM'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Modality-toolkit'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/SuperSampler'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ZArchive'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/dblib'
           compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/NLC'
           compiling dir: '/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/supercolliderjs/lib/supercollider-js'
           pass 1 done
debug  : numentries = 3451768 / 103961520 = 0.033
           15080 method selectors, 6894 classes
           method table size 80724024 bytes, big table size 831692160
           Number of Symbols 36990
           Byte Code Size 1716606
           compiled 1683 files in 1.78 seconds
           Info: 58 methods are currently overwritten by extensions. To see which, execute:
           MethodOverride.printAll
           compile done
debug  : Class tree inited in 0.03 seconds
debug  : Ctk init class runs
debug  : Cleaning up temp synthdefs...
debug  : WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Extensions/Dictionary/extDictionary-++.sc' overwrites Dictionary:++ in main class library.
           WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Improvements/extUgen-isUGen.sc' overwrites UGen:isUGen in main class library.
debug  : Intentional overwrites must be put in a 'SystemOverwrites' subfolder.
           *** Welcome to SuperCollider 3.8.0. *** For help type cmd-d.
debug  : SuperColliderJS.interpret("civuknaop0000p8frlhv967yc","SuperColliderJS.sclangConf = \"/Users/tatecarson/Library/Application Support/SuperCollider/sclang_conf.yaml\";__NL____NL__",nil,true,true,true);
debug  :
           SUPERCOLLIDERJS:civuknaop0000p8frlhv967yc:CAPTURE:START
debug  :
           SUPERCOLLIDERJS:civuknaop0000p8frlhv967yc:CAPTURE:END
           SUPERCOLLIDERJS:civuknaop0000p8frlhv967yc:START:Result
           SUPERCOLLIDERJS:civuknaop0000p8frlhv967yc:CHUNK:"SuperColliderJS"
           SUPERCOLLIDERJS:civuknaop0000p8frlhv967yc:END:Result
           SUPERCOLLIDERJS.interpreted
           ->
debug  : SuperColliderJS.interpret("civuknap10001p8frnok7ihjm","(1..8).pyramid",nil,false,false,false);
debug  : SuperColliderJS.interpret("civuknap10002p8frfycg8qnb","1 + 1 oh no this is a syntax error",nil,false,false,false);
debug  : SuperColliderJS.interpret("civuknap20003p8frnvtabghm","1 + 1.integerDoesntHaveThisMethod",nil,false,false,false);
debug  :
           SUPERCOLLIDERJS:civuknap10001p8frnok7ihjm:CAPTURE:START
           SUPERCOLLIDERJS:civuknap10001p8frnok7ihjm:CAPTURE:END
           SUPERCOLLIDERJS:civuknap10001p8frnok7ihjm:START:Result
           SUPERCOLLIDERJS:civuknap10001p8frnok7ihjm:CHUNK:[1,1,2,1,2,3,1,2,3,4,1,2,3,4,5,1,2,3,4,5,6,1,2,3,4,5,6,7,1,2,3,4,5,6,7,8]
           SUPERCOLLIDERJS:civuknap10001p8frnok7ihjm:END:Result
           SUPERCOLLIDERJS.interpreted
           ->
           SUPERCOLLIDERJS:civuknap10002p8frfycg8qnb:CAPTURE:START
           ERROR: syntax error, unexpected NAME, expecting $end
             in file 'selected text'
             line 1 char 8:
             1 + 1 oh no this is a syntax error
                   ^^
           -----------------------------------
           ERROR: Command line parse failed
           SUPERCOLLIDERJS:civuknap10002p8frfycg8qnb:CAPTURE:END
           SUPERCOLLIDERJS:civuknap10002p8frfycg8qnb:START:SyntaxError
           SUPERCOLLIDERJS:civuknap10002p8frfycg8qnb:CHUNK:null
           SUPERCOLLIDERJS:civuknap10002p8frfycg8qnb:END:SyntaxError
           SUPERCOLLIDERJS.interpreted
           ->
Result:
[ 1,
  1,
  2,
  1,
  2,
  3,
  1,
  2,
  3,
  4,
  1,
  2,
  3,
  4,
  5,
  1,
  2,
  3,
  4,
  5,
  6,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8 ]
Error:
SCLangError {
  data: {},
  type: 'SyntaxError',
  error: { msg: null, file: null, line: null, charPos: null, code: '' } }
debug  :
           SUPERCOLLIDERJS:civuknap20003p8frnvtabghm:CAPTURE:START
debug  :
           SUPERCOLLIDERJS:civuknap20003p8frnvtabghm:CAPTURE:END
debug  :
           SUPERCOLLIDERJS:civuknap20003p8frnvtabghm:START:Error
           SUPERCOLLIDERJS:civuknap20003p8frnvtabghm:CHUNK:{"selector": "integerDoesntHaveThisMethod","what": "DoesNotUnderstandError","args": [],"receiver": {"asString": "1","class": "Integer"},"class": "DoesNotUnderstandError","path": "civuknap20003p8frnvtabghm","errorString": "ERROR: Message 'integerDoesntHaveThisMethod' not understood."}
           SUPERCOLLIDERJS:civuknap20003p8frnvtabghm:END:Error
           SUPERCOLLIDERJS.interpreted
Error:
SCLangError {
  data: {},
  type: 'Error',
  error:
   { selector: 'integerDoesntHaveThisMethod',
     what: 'DoesNotUnderstandError',
     args: [],
     receiver: { asString: '1', class: 'Integer' },
     class: 'DoesNotUnderstandError',
     path: 'civuknap20003p8frnvtabghm',
     errorString: 'ERROR: Message \'integerDoesntHaveThisMethod\' not understood.' } }
debug  : ->

**dyads/ synth**

error:
TypeError: dryad.children.map is not a function
    at DryadTree._makeTree (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadTree.js:403:64)
    at /Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadTree.js:404:23
    at Array.map (native)
    at DryadTree._makeTree (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadTree.js:403:64)
    at /Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadTree.js:404:23
    at Array.map (native)
    at DryadTree._makeTree (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadTree.js:403:64)
    at new DryadTree (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadTree.js:54:24)
    at DryadPlayer.setRoot (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadPlayer.js:100:19)
    at DryadPlayer.play (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/node_modules/dryadic/lib/DryadPlayer.js:202:14)
    at Object.<anonymous> (/Users/tatecarson/Documents/Supercollider/_OrgExamples/Tutorials/supercolliderjs-examples/node/dryads/synth.js:22:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by crucialfelix** [comment]
I was super stressed and hitting a deadline (for the UDK class) so I did realize after publishing that I published a few that were for a changed API.

I'll get these fixed up soon. Thanks !

lang/sclang-interpret is supposed to do that - it is showing how a raw error is posted.  I want to make an error reporter for this that formats that for the console.
